right_format = '$aws'

[directory]
format = '[$path](fg:69 bold)[$read_only]($read_only_style) '
truncation_length = 100
truncate_to_repo = false

[git_branch]
format = '[$symbol$branch]($style)([â†’](dimmed)[$remote_name](fg:purple bold dimmed)) '
always_show_remote = true

[aws]
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )](fg:216 bold)'
